### ISSUE TITLE
GetInputmaskCnt error

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerSwap#21]
```shell
2a98cedbbbfd48f299b979816f13f782 | Inputmaks shares used: <nil>
2a98cedbbbfd48f299b979816f13f782 | panic: runtime error: invalid memory address or nil pointer dereference
2a98cedbbbfd48f299b979816f13f782 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaa377a]
2a98cedbbbfd48f299b979816f13f782 | goroutine 8 [running]:
2a98cedbbbfd48f299b979816f13f782 | math/big.(*Int).Int64(...)
2a98cedbbbfd48f299b979816f13f782 |      /usr/local/go/src/math/big/int.go:372
2a98cedbbbfd48f299b979816f13f782 | github.com/initc3/HoneyBadgerSwap/src/go/utils.GetInputmaskCnt(0xc000279170, 0x7, 0xc0000ab110, 0x3e)
2a98cedbbbfd48f299b979816f13f782 |      /go/src/github.com/initc3/HoneyBadgerSwap/src/go/utils/utils_hbswap.go:387 +0x19a
2a98cedbbbfd48f299b979816f13f782 | main.genInputmask()
2a98cedbbbfd48f299b979816f13f782 |      /go/src/github.com/initc3/HoneyBadgerSwap/src/go/server/server.go:47 +0xab
2a98cedbbbfd48f299b979816f13f782 | created by main.main
2a98cedbbbfd48f299b979816f13f782 |      /go/src/github.com/initc3/HoneyBadgerSwap/src/go/server/server.go:332 +0x5ef
```

**Comment by sbellem** [comment]
```shell
2c69f23706cb4f38be3fa10d60963a13 | 2021/04/21 04:00:24 Inputmask shares used: <nil>
2c69f23706cb4f38be3fa10d60963a13 | panic: runtime error: invalid memory address or nil pointer dereference
2c69f23706cb4f38be3fa10d60963a13 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaa37a5]
2c69f23706cb4f38be3fa10d60963a13 | goroutine 34 [running]:
2c69f23706cb4f38be3fa10d60963a13 | math/big.(*Int).Int64(...)
2c69f23706cb4f38be3fa10d60963a13 |      /usr/local/go/src/math/big/int.go:372
2c69f23706cb4f38be3fa10d60963a13 | github.com/initc3/HoneyBadgerSwap/src/go/utils.GetInputmaskCnt(0xc000259210, 0x7, 0xc000240868, 0xc)
2c69f23706cb4f38be3fa10d60963a13 |      /go/src/github.com/initc3/HoneyBadgerSwap/src/go/utils/utils_hbswap.go:386 +0x165
2c69f23706cb4f38be3fa10d60963a13 | main.genInputmask()
2c69f23706cb4f38be3fa10d60963a13 |      /go/src/github.com/initc3/HoneyBadgerSwap/src/go/server/server.go:49 +0xab
2c69f23706cb4f38be3fa10d60963a13 | created by main.main
2c69f23706cb4f38be3fa10d60963a13 |      /go/src/github.com/initc3/HoneyBadgerSwap/src/go/server/server.go:325 +0x58f
4379861dd3b748dcb88bbf92c3682dbb | 2021/04/21 04:02:25 Inputmask shares used: 12
```
