### ISSUE TITLE
Deploy mpc network to the ground

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerSwap#3]

**Comment by sbellem** [comment]
See if secrets can be mounted from local file: https://docs.docker.com/cloud/ecs-compose-examples/#secrets

**Comment by sbellem** [comment]
Happening when only dev geth node & mpc nodes are deployed on aws, without client requests/actions. (No contract deployed, not pool initialized, no deposits, no trades.)

```shell
d809820ae0fc4a77a079c10652997c72  | Inputmaks shares used: <nil>                                                                                                              
d809820ae0fc4a77a079c10652997c72  | panic: runtime error: invalid memory address or nil pointer dereference                            
d809820ae0fc4a77a079c10652997c72  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x978884]                             
d809820ae0fc4a77a079c10652997c72  | goroutine 7 [running]:                                                                                                                               
d809820ae0fc4a77a079c10652997c72  | math/big.(*Int).Int64(...)                                                                                                                   
d809820ae0fc4a77a079c10652997c72  |     /usr/local/go/src/math/big/int.go:374                                                          
d809820ae0fc4a77a079c10652997c72  | github.com/initc3/HoneyBadgerSwap/src/go/utils.GetInputmaskCnt(0xc0000ac798, 0x0)                  
d809820ae0fc4a77a079c10652997c72  |     /go/src/github.com/initc3/HoneyBadgerSwap/src/go/utils/utils_hbswap.go:327 +0x144                                                                 
d809820ae0fc4a77a079c10652997c72  | main.genInputmask(0x7ffed7e73b65, 0x8)                                                                                                    
d809820ae0fc4a77a079c10652997c72  |     /go/src/github.com/initc3/HoneyBadgerSwap/src/go/server/server.go:58 +0x45                     
d809820ae0fc4a77a079c10652997c72  | created by main.main                                                                               
d809820ae0fc4a77a079c10652997c72  |     /go/src/github.com/initc3/HoneyBadgerSwap/src/go/server/server.go:306 +0x29c                                                                      
d809820ae0fc4a77a079c10652997c72  | exit status 2
```

**Comment by sbellem** [comment]
# Certificate
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/acm/request-certificate.html

**Comment by amiller** [comment]
<img src="https://user-images.githubusercontent.com/71644/112510801-cb784b00-8d5f-11eb-8ad7-5ef76ab3f616.png" alt="image" width="250">
