### ISSUE TITLE
MP-SPDZ upgrade

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerSwap#30]
Problems with compiling some `*.mpc` programs:

* `hbswap_add_liquidity`
* `hbswap_remove_liquidity`
* `hbswap_trade`
* `hbswap_calc_individual_price`

Example of error:

```console
Compiling file /usr/src/MP-SPDZ/Programs/Source/hbswap_trade.mpc
Traceback (most recent call last):
  File "/usr/src/MP-SPDZ/Compiler/instructions_base.py", line 827, in check_args
    ArgFormats[f].check(arg)
  File "/usr/src/MP-SPDZ/Compiler/instructions_base.py", line 662, in check
    raise ArgumentError(arg, "Wrong register type '%s', expected '%s'" % \
Compiler.exceptions.ArgumentError: (s80, "Wrong register type 's', expected 'ci'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./compile.py", line 111, in <module>
    main()
  File "./compile.py", line 108, in main
    compilation()
  File "./compile.py", line 96, in compilation
    prog = Compiler.run(args, options)
  File "/usr/src/MP-SPDZ/Compiler/compilerLib.py", line 77, in run
    exec(compile(infile.read(), infile.name, 'exec'), VARS)
  File "/usr/src/MP-SPDZ/Programs/Source/hbswap_trade.mpc", line 88, in <module>
    main()
  File "/usr/src/MP-SPDZ/Programs/Source/hbswap_trade.mpc", line 65, in main
    write_sfix(change_A)
  File "/usr/src/MP-SPDZ/Programs/Source/hbswap_trade.mpc", line 15, in write_sfix
    writesharestofile(x.v)
  File "/usr/src/MP-SPDZ/Compiler/instructions_base.py", line 788, in __init__
    self.check_args()
  File "/usr/src/MP-SPDZ/Compiler/instructions_base.py", line 829, in check_args
    raise CompilerError('Invalid argument %d "%s" to instruction: %s'
Compiler.exceptions.CompilerError: Invalid argument 0 "s80" to instruction: writesharestofile 1, s80
Wrong register type 's', expected 'ci'
```

**Comment by sbellem** [comment]
Done.
