### ISSUE TITLE
aiohttp.http_exceptions.BadStatusLine: 400, 'invalid HTTP method'

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerSwap#6]
Happens when initializing the pool via `scripts/init_pool.sh`.

Server side logs:

```shell
910a6d4f2766456990e6a2a7b772024b  | Error handling request
910a6d4f2766456990e6a2a7b772024b  | Traceback (most recent call last):
910a6d4f2766456990e6a2a7b772024b  |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
910a6d4f2766456990e6a2a7b772024b  |     messages, upgraded, tail = self._request_parser.feed_data(data)
910a6d4f2766456990e6a2a7b772024b  |   File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
910a6d4f2766456990e6a2a7b772024b  | aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
```

Cient-side logs:

```shell
$ docker-compose -f liquidity-provider.yml up init.pool
init.pool_1  | Parsing config file:  /opt/hbswap/conf/client.toml
init.pool_1  | Eth network:  testnet
init.pool_1  | Eth hostname:  kovan.infura.io
init.pool_1  | Eth http endpoint:  https://kovan.infura.io/v3/6a82d2519efb4d748c02552e02e369c1
init.pool_1  | depositETH ...
init.pool_1  | FundEth ...
init.pool_1  | 2021/03/09 14:38:51 transferETH ...
init.pool_1  | Sending 10 wei from 0x096f48173c8EB3849bb415F62D3113CB3b90C640 to 0xeF860fb0634474AE0E6ceC1A8E0dBE7C70A280A5
init.pool_1  | Deposit user 0xeF860fb0634474AE0E6ceC1A8E0dBE7C70A280A5 10 token 0x0000000000000000000000000000000000000000
init.pool_1  | 2021/03/09 14:38:59 transferETH ...
init.pool_1  | 2021/03/09 14:38:59 transfer ctx: context.Background
init.pool_1  | Sending 1476299999999990 wei from 0x096f48173c8EB3849bb415F62D3113CB3b90C640 to 0xeF860fb0634474AE0E6ceC1A8E0dBE7C70A280A5
init.pool_1  | On-chain balance user 0xeF860fb0634474AE0E6ceC1A8E0dBE7C70A280A5 token 0x0000000000000000000000000000000000000000: 130
```

**Comment by sbellem** [comment]
See https://github.com/aio-libs/aiohttp/issues/5358
